---
step-runner-config:
  global-defaults:
    organization: platform
    application-name: ref-nodejs-npm
    service-name: hello

  container-image-static-vulnerability-scan:
  - name: OpenSCAP - Vulnerability - DataStream
    implementer: OpenSCAP
    config:
      oscap-input-definitions-uri: https://www.redhat.com/security/data/metrics/ds/v2/RHEL8/rhel-8.ds.xml.bz2
      oscap-tailoring-uri: https://raw.githubusercontent.com/ploigos-reference-apps/ploigos-example-oscap-content/main/xccdf_com.ploigos_profile_default_cve_ploigos_reference_apps-tailoring.xml
      oscap-profile: xccdf_com.ploigos_profile_default_cve_ploigos_reference_quarkus_mvn

  deploy:
  - implementer: ArgoCD
    config:
      deployment-config-repo: http://gitea:3000/platform/reference-nodejs-npm-cloud-resources_workflow-typical.git
      deployment-config-helm-chart-path: charts/reference-app-deploy
      deployment-config-helm-chart-values-file-image-tag-yq-path: 'image.tag'
    environment-config:
      DEV:
        deployment-config-helm-chart-environment-values-file: values-DEV.yaml
      TEST:
        deployment-config-helm-chart-environment-values-file: values-TEST.yaml
      PROD:
        deployment-config-helm-chart-environment-values-file: values-PROD.yaml

  uat:
  - implementer: NpmXunitIntegrationTest
    config:
      npm-test-script: 'test:uat:cicd'
      test-reports-dir: 'uat-results/'
      target-host-env-var-name: CYPRESS_BASE_URL
      npm-envs:
        NO_COLOR: '1'
